sources:
  - LINESeedSans-Thin.glyphspackage
  - LINESeedSans-Regular.glyphspackage
  - LINESeedSans-Bold.glyphspackage
  - LINESeedSans-ExtraBold.glyphspackage
  - LINESeedSans-Heavy.glyphspackage
familyName: LINE Seed Sans
autohintTTF: false
autohintOTF: false
extraStaticFontmakeArgs: --subroutinizer compreffor
