sources:
  - LINESeedJP-Thin.glyphspackage
  - LINESeedJP-Regular.glyphspackage
  - LINESeedJP-Bold.glyphspackage
  - LINESeedJP-ExtraBold.glyphspackage
familyName: LINE Seed JP
autohintTTF: false
autohintOTF: false
extraStaticFontmakeArgs: --subroutinizer compreffor
