sources:
  - LINESeedJP-Thin.glyphs
  - LINESeedJP-Regular.glyphs
  - LINESeedJP-Bold.glyphs
  - LINESeedJP-ExtraBold.glyphs
familyName: LINE Seed JP
autohintTTF: false
autohintOTF: false
extraStaticFontmakeArgs: --subroutinizer compreffor
